services:
  chroma:
    image: chromadb/chroma
    container_name: flexible-rag-chroma-production
    volumes:
      - chroma:/chroma/chroma

  api:
    container_name: flexible-rag-api-production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:8000"
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - COHERE_API_KEY=${COHERE_API_KEY}
    depends_on:
      - chroma

volumes:
  chroma:
