site_name: Flexible RAG
site_url: https://flexiblerag.thangved.com
repo_url: https://github.com/thangved/flexible-rag
repo_name: thangved/flexible-rag
remote_branch: gh-pages
site_author: Kim Minh Thắng
site_description: A flexible RAG for your project

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - header.autohide
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - toc.integrate
  palette:
    primary: white
  font:
    text: Montserrat
    code: JetBrains Mono
  logo: assets/logo.svg
  favicon: assets/logo.svg

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
  - RESTful API: api/restful.md
  - API reference:
      - flexible-rag: reference/

plugins:
  - search
  - tags
  - gen-files:
      scripts:
        - scripts/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/objects.inv
            - https://mkdocstrings.github.io/autorefs/objects.inv
            - https://mkdocstrings.github.io/griffe/objects.inv
            - https://python-markdown.github.io/objects.inv
          options:
            allow_inspection: true
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          filters: ["!^_"]
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          parameter_headings: true
          preload_modules: [mkdocstrings]
          relative_crossrefs: true
          scoped_crossrefs: true
          separate_signature: true
          show_bases: false
          show_inheritance_diagram: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_source: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          summary: true
          unwrap_annotated: true
  - blog:
      enabled: true
      archive_toc: true
      authors: true
  - rss:
      match_path: docs/blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      enabled: !ENV [CI, false]
  - offline
  - git-committers:
      repository: thangved/flexible-rag
      branch: main
  - git-revision-date-localized
  - mkdocs_github_changelog
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
  - swagger-ui-tag
  - autorefs
  - mike

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thangved
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thangved
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/thangved
  version:
    provider: mike
    default: stable
    alias: true
  analytics:
    provider: google
    property: G-GTY506MC92
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage

extra_css:
  - stylesheets/extra.css

extra_javascript:
- https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js

copyright: Copyright &copy; 2024 Kim Minh Thắng
