[tool.poetry]
name = "flexible-rag"
version = "0.1.0"
description = "Flexible RAG"
authors = ["Kim Minh Thang <thangved02@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
