[tool.poetry]
name = "flexible-rag"
version = "0.1.0"
description = "Flexible RAG"
authors = ["Kim Minh Thang <thangved02@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.core.dependencies]
langchain-core = "^0.3.12"
langchain-chroma = ">=0.1.2"
pydantic = "^2.9.2"
langchain-cohere = "^0.3.1"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"
pytest-cov = "^5.0.0"
trio = "^0.27.0"



[tool.poetry.group.api.dependencies]
fastapi = {extras = ["standard"], version = "^0.115.2"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
