[tool.poetry]
name = "flexible-rag"
version = "0.1.0"
description = "Flexible RAG"
authors = ["Kim Minh Thang <thangved02@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.core.dependencies]
langchain-core = "^0.3.12"
langchain-chroma = ">=0.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
