name: Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
        name: Setup cache
      - uses: actions/cache@v4
        name: Use cache
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install poetry
        name: Install poetry
      - run: poetry install --with docs
        name: Install packages
      - run: poetry add fastapi
        name: Install FastAPI
      - run: poetry run python build_openapi.py
        name: Buidl API docs
      - run: poetry run mkdocs gh-deploy --force
        name: Deploy
